server:
  port: 4000
spring:
  config:
    import: messages.yml
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres

app:
  bot:
    telegram:
      username: gmail_flow_bot
      token: hidden token ;)